/** @jsx React.DOM */
"use strict";

var React = require("react");
var _ = require("underscore");

var DidClickOutside = require("../mixins/did_click_outside.jsx");
var LocusDiagram = require("../viz/locus_diagram.jsx");
var MultiAlignmentViewer = require("./multi_alignment_viewer.jsx");
var SequenceNeighborsModel = require("../../models/sequence_neighbors_model.jsx");

var HEIGHT_WITH_SEQUENCE = 580;
var HEIGHT_WITHOUT_SEQUENCE = 390;

module.exports = React.createClass({
	mixins: [DidClickOutside],

	propTypes: {
		locusDisplayName: React.PropTypes.string.isRequired,
		locusId: React.PropTypes.number.isRequired,
		onExit: React.PropTypes.func.isRequired
	},

	getInitialState: function () {
		return {
			showSequence: false,
			neighborModelAttr: null
		};
	},

	render: function () {
		var _height = this.state.showSequence ? HEIGHT_WITH_SEQUENCE : HEIGHT_WITHOUT_SEQUENCE;
		var _style = {
			position: "fixed",
			bottom: 0,
			left: 0,
			right: 0,
			height: _height,
			background: "#efefef",
			padding: "1rem",
			zIndex: 1
		};
		var _exitStyle = {
			position: "absolute",
			top: "0.5rem",
			right: "1rem",
			color: "black"
		};

		var locusDiagramNode = null;
		if (this.state.neighborModelAttr) {
			var attr = this.state.neighborModelAttr;
			locusDiagramNode = (<LocusDiagram
				contigData={attr.contigData}
				data={attr.data}
				domainBounds={attr.domainBounds}
				focusLocusDisplayName={this.props.locusDisplayName}
				showSubFeatures={false}
				watsonTracks={Math.abs(attr.trackDomain[1])}
				crickTracks={Math.abs(attr.trackDomain[0])}
			/>);
		}

		var sequenceNode = this._getSequenceNode();
		return (<div style={_style}>
			<h1>
				{this.props.locusDisplayName}
				<a onClick={this.props.onExit} style={_exitStyle}><i className="fa fa-times"></i></a>
			</h1>
			{locusDiagramNode}
			{sequenceNode}
		</div>);
	},

	componentDidMount: function () {
	    this._fetchNeighborData();  
	},

	didClickOutside: function () {
		this.props.onExit();
	},

	_fetchNeighborData: function () {
		var neighborModel = new SequenceNeighborsModel({ id: this.props.locusId });
		neighborModel.fetch( (err, response) => {
			if (this.isMounted()) this.setState({
				neighborModelAttr: neighborModel.attributes.mainStrain
			});
		});
	},

	_getSequenceNode: function () {
		var node;
		if (this.state.showSequence) {
			// TEMP fake some sequence data
		var exampleData = {
			sequences: [
				{
					name: "S288C",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				},
				{
					name: "CEN.PK",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACTAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				},
				{
					name: "FL100",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				},
				{
					name: "D273-10B",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				},
				{
					name: "JK9-3D",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				},
				{
					name: "RM11-1a",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				},
				{
					name: "SK1",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				},
				{
					name: "W303",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				},
				{
					name: "Y55",
					sequence: "ATGGCAAGACGCAGATTACCAGACAGACCACCAAATGGAATAGGAGCCGGTGAACGGCCGAGACTGGTACCTAGGCCTATTAACGTACAAGACTCGGTGAACCGACTAACGAAACCGTTCAGGGTCCCGTACAAGAACACGCACATCCCGCCCGCTGCTGGTAGAATCGCCACCGGGTCTGATAATATCGTAGGAGGAAGGAGCTTGAGGAAAAGATCAGCGACTGTATGTTATTCCGGCTTGGATATAAATGCGGACGAAGCAGAGTACAACAGCCAAGACATAAGTTTTTCTCAGTTGACTAAACGACGGAAGGATGCTCTTAGTGCTCAAAGGTTGGCCAAGGATCCGACA"
				}
			],
			segments: [
				{
					domain: [0, 88],
					visible: false
				},
				{
					domain: [88, 89],
					visible: true
				},
				{
					domain: [90, 354],
					visble: false
				}
			]
		};
			node = <MultiAlignmentViewer segments={exampleData.segments} sequences={exampleData.sequences} />;
		} else {
			node = <a className="button secondary small" onClick={this._showSequence}>Show Sequence</a>
		}
		return node;
	},

	_showSequence: function (e) {
		e.stopPropagation();
		e.nativeEvent.stopImmediatePropagation();
		this.setState({ showSequence: true });
	}
});
