export const FETCH_DOWNLOADS_RESULTS_SUCCESS ="FETCH_DOWNLOADS_RESULTS_SUCCESS";
export const FETCH_DOWNLOADS_MENU = "FETCH_DOWNLOADS_MENU";
export const START_PENDING = "START_PENDING";
export const GET_SELECTED_NODE = "GET_SELECTED_NODE";
export const DELETE_SELECTED_NODE = "REMOVE_SELECTED_NODE";
export const GET_SELECTED_LEAF = "GET_SELECTED_LEAF";
export const DELETE_SELECTED_LEAF = "DELETE_SELECTED_LEAF";

