export const allTags = [
  'Classical phenotype information', 
  'Delay', 
  'Fast Track', 
  'GO information', 
  'GO needs review', 
  'Gene model', 
  'Headline needs review', 
  'Headline reviewed', 
  'Headline information', 
  'High Priority',
  'Homology/Disease', 
  'HTP phenotype', 
  'Non-phenotype HTP', 
  'Not yet curated', 
  'Paragraph needs review', 
  'Paragraph not needed', 
  'Pathways', 
  'Phenotype needs review', 
  'Phenotype uncuratable',
  'Post-translational modifications', 
  'Regulation information'
];
