-- Generated by Ora2Pg, the Oracle database Schema converter, version 17.4
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sgd-nex2-db.stanford.edu;sid=SGD

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

--
-- Insert into deletelog table whenever a row is deleted from a table
--
CREATE OR REPLACE FUNCTION insertdeletelog (p_table text, p_key bigint, p_row text, p_user text)  RETURNS VOID AS $body$
BEGIN

    INSERT INTO nex.deletelog
        (tab_name, primary_key, deleted_row, created_by)
    VALUES
        (upper(p_table), p_key, p_row, p_user);

END;

$body$ LANGUAGE PLPGSQL;
GRANT EXECUTE on FUNCTION insertdeletelog (p_table text, p_key bigint, p_row text, p_user text) to CURATOR;
REVOKE ALL ON FUNCTION insertdeletelog (p_table text, p_key bigint, p_row text, p_user text) FROM PUBLIC;


--
-- Insert into updatelog table whenever a row is updated in a table
--
CREATE OR REPLACE FUNCTION insertupdatelog (p_table text, p_column text, p_key bigint, p_old text, p_new text, p_user text)  RETURNS VOID AS $body$
BEGIN

    INSERT INTO nex.updatelog
        (tab_name, col_name, primary_key, old_value, new_value, created_by)
    VALUES
        (upper(p_table), upper(p_column), p_key, p_old, p_new, p_user);

END;

$body$ LANGUAGE PLPGSQL;
GRANT EXECUTE on FUNCTION insertupdatelog (p_table text, p_column text, p_key bigint, p_old text, p_new text, p_user text) to CURATOR;
REVOKE ALL ON FUNCTION insertupdatelog (p_table text, p_column text, p_key bigint, p_old text, p_new text, p_user text) FROM PUBLIC;


--
-- Automatic insert into the arch_locuschange table for gene_names and qualifiers
--
CREATE OR REPLACE FUNCTION insertlocuschange (p_dbentityId text, p_sourceName text, p_changeType text, p_oldValue text, p_newValue text, p_changeDate timestamp, p_user text) RETURNS VOID AS $body$
DECLARE

   v_sourceID   source.source_id%TYPE;

BEGIN

    SELECT source_id INTO v_sourceID
    FROM SOURCE
    WHERE display_name = p_sourceName;

    INSERT INTO arch_locuschange
        (dbentity_id, source_id, change_type, old_value, new_value, date_changed, changed_by)
    VALUES
        (p_dbentityID, v_sourceID, p_changeType, p_oldValue, p_newValue, p_changeDate, p_user);

END;

$body$ LANGUAGE PLPGSQL;
GRANT EXECUTE on FUNCTION insertlocuschange (p_dbentityId text, p_sourceName text, p_changeType text, p_oldValue text, p_newValue text, p_changeDate timestamp, p_user text) to CURATOR;
REVOKE ALL ON FUNCTION insertlocuschange (p_dbentityId text, p_sourceName text, p_changeType text, p_oldValue text, p_newValue text, p_changeDate timestamp, p_user text) FROM PUBLIC;


--
-- Automatic insert into SGDID table
--
CREATE OR REPLACE FUNCTION insertsgdid (p_sgdid text, p_source text, p_sgdidClass text, p_sgdidStatus text, p_user text) RETURNS VOID AS $body$
DECLARE

    v_source_id   sgdid.source_id%TYPE;
    v_objurl      sgdid.obj_url%TYPE;

BEGIN

    select source_id INTO v_source_id
    from source
    where display_name = p_source;

    v_objurl := CONCAT('/sgdid/', p_sgdid);

    INSERT INTO sgdid
        (format_name, display_name, obj_url, source_id, subclass, sgdid_status, created_by)
    VALUES
        (p_sgdid, p_sgdid, v_objurl, v_source_id, p_sgdidClass, p_sgdidStatus, p_user);

END;

$body$ LANGUAGE PLPGSQL;
GRANT EXECUTE on FUNCTION insertsgdid (p_sgdid text, p_source text, p_sgdidClass text, p_sgdidStatus text, p_user text) to CURATOR;
REVOKE ALL ON FUNCTION insertsgdid (p_sgdid text, p_source text, p_sgdidClass text, p_sgdidStatus text, p_user text) FROM PUBLIC;      
