-- Generated by Ora2Pg, the Oracle database Schema converter, version 17.4
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sgd-nex2-db.stanford.edu;sid=SGD

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

-- Set privilege on TABLE ALLELE
ALTER TABLE nex.allele OWNER TO nex;
GRANT ALL ON nex.allele TO nex;
REVOKE ALL ON nex.allele FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.allele TO curator;
GRANT SELECT ON nex.allele TO PUBLIC;

-- Set privilege on TABLE APO
ALTER TABLE nex.apo OWNER TO nex;
GRANT ALL ON nex.apo TO nex;
REVOKE ALL ON nex.apo FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.apo TO curator;
GRANT SELECT ON nex.apo TO PUBLIC;

-- Set privilege on TABLE APO_ALIAS
ALTER TABLE nex.apo_alias OWNER TO nex;
GRANT ALL ON nex.apo_alias TO nex;
REVOKE ALL ON nex.apo_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.apo_alias TO curator;
GRANT SELECT ON nex.apo_alias TO PUBLIC;

-- Set privilege on TABLE APO_RELATION
ALTER TABLE nex.apo_relation OWNER TO nex;
GRANT ALL ON nex.apo_relation TO nex;
REVOKE ALL ON nex.apo_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.apo_relation TO curator;
GRANT SELECT ON nex.apo_relation TO PUBLIC;

-- Set privilege on TABLE APO_URL
ALTER TABLE nex.apo_url OWNER TO nex;
GRANT ALL ON nex.apo_url TO nex;
REVOKE ALL ON nex.apo_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.apo_url TO curator;
GRANT SELECT ON nex.apo_url TO PUBLIC;

-- Set privilege on TABLE ARCH_CONTIG
ALTER TABLE nex.arch_contig OWNER TO nex;
GRANT ALL ON nex.arch_contig TO nex;
REVOKE ALL ON nex.arch_contig FROM PUBLIC;
GRANT SELECT,INSERT ON nex.arch_contig TO curator;
GRANT SELECT ON nex.arch_contig TO PUBLIC;

-- Set privilege on TABLE ARCH_CONTIGCHANGE
ALTER TABLE nex.arch_contigchange OWNER TO nex;
GRANT ALL ON nex.arch_contigchange TO nex;
REVOKE ALL ON nex.arch_contigchange FROM PUBLIC;
GRANT SELECT,INSERT ON nex.arch_contigchange TO curator;
GRANT SELECT ON nex.arch_contigchange TO PUBLIC;

-- Set privilege on TABLE ARCH_DNASEQUENCEANNOTATION
ALTER TABLE nex.arch_dnasequenceannotation OWNER TO nex;
GRANT ALL ON nex.arch_dnasequenceannotation TO nex;
REVOKE ALL ON nex.arch_dnasequenceannotation FROM PUBLIC;
GRANT SELECT,INSERT ON nex.arch_dnasequenceannotation TO curator;
GRANT SELECT ON nex.arch_dnasequenceannotation TO PUBLIC;

-- Set privilege on TABLE ARCH_DNASUBSEQUENCE
ALTER TABLE nex.arch_dnasubsequence OWNER TO nex;
GRANT ALL ON nex.arch_dnasubsequence TO nex;
REVOKE ALL ON nex.arch_dnasubsequence FROM PUBLIC;
GRANT SELECT,INSERT ON nex.arch_dnasubsequence TO curator;
GRANT SELECT ON nex.arch_dnasubsequence TO PUBLIC;

-- Set privilege on TABLE ARCH_LITERATUREANNOTATION
ALTER TABLE nex.arch_literatureannotation OWNER TO nex;
GRANT ALL ON nex.arch_literatureannotation TO nex;
REVOKE ALL ON nex.arch_literatureannotation FROM PUBLIC;
GRANT SELECT,INSERT ON nex.arch_literatureannotation TO curator;
GRANT SELECT ON nex.arch_literatureannotation TO PUBLIC;

-- Set privilege on TABLE ARCH_LOCUSCHANGE
ALTER TABLE nex.arch_locuschange OWNER TO nex;
GRANT ALL ON nex.arch_locuschange TO nex;
REVOKE ALL ON nex.arch_locuschange FROM PUBLIC;
GRANT SELECT,INSERT ON nex.arch_locuschange TO curator;
GRANT SELECT ON nex.arch_locuschange TO PUBLIC;

-- Set privilege on TABLE ARCH_PROTEINSEQUENCEANNOTATION
ALTER TABLE nex.arch_proteinsequenceannotation OWNER TO nex;
GRANT ALL ON nex.arch_proteinsequenceannotation TO nex;
REVOKE ALL ON nex.arch_proteinsequenceannotation FROM PUBLIC;
GRANT SELECT,INSERT ON nex.arch_proteinsequenceannotation TO curator;
GRANT SELECT ON nex.arch_proteinsequenceannotation TO PUBLIC;

-- Set privilege on TABLE AUTHORRESPONSE
ALTER TABLE nex.authorresponse OWNER TO nex;
GRANT ALL ON nex.authorresponse TO nex;
REVOKE ALL ON nex.authorresponse FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.authorresponse TO curator;
GRANT SELECT ON nex.authorresponse TO PUBLIC;

-- Set privilege on TABLE BINDINGMOTIFANNOTATION
ALTER TABLE nex.bindingmotifannotation OWNER TO nex;
GRANT ALL ON nex.bindingmotifannotation TO nex;
REVOKE ALL ON nex.bindingmotifannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.bindingmotifannotation TO curator;
GRANT SELECT ON nex.bindingmotifannotation TO PUBLIC;

-- Set privilege on TABLE BOOK
ALTER TABLE nex.book OWNER TO nex;
GRANT ALL ON nex.book TO nex;
REVOKE ALL ON nex.book FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.book TO curator;
GRANT SELECT ON nex.book TO PUBLIC;

-- Set privilege on TABLE CHEBI
ALTER TABLE nex.chebi OWNER TO nex;
GRANT ALL ON nex.chebi TO nex;
REVOKE ALL ON nex.chebi FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.chebi TO curator;
GRANT SELECT ON nex.chebi TO PUBLIC;

-- Set privilege on TABLE CHEBI_ALIAS
ALTER TABLE nex.chebi_alias OWNER TO nex;
GRANT ALL ON nex.chebi_alias TO nex;
REVOKE ALL ON nex.chebi_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.chebi_alias TO curator;
GRANT SELECT ON nex.chebi_alias TO PUBLIC;

-- Set privilege on TABLE CHEBI_RELATION
--ALTER TABLE nex.chebi_relation OWNER TO nex;
--GRANT ALL ON nex.chebi_relation TO nex;
--REVOKE ALL ON nex.chebi_relation FROM PUBLIC;
--GRANT SELECT,INSERT,UPDATE,DELETE ON nex.chebi_relation TO curator;
--GRANT SELECT ON nex.chebi_relation TO PUBLIC;

-- Set privilege on TABLE CHEBI_URL
ALTER TABLE nex.chebi_url OWNER TO nex;
GRANT ALL ON nex.chebi_url TO nex;
REVOKE ALL ON nex.chebi_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.chebi_url TO curator;
GRANT SELECT ON nex.chebi_url TO PUBLIC;

-- Set privilege on TABLE COLLEAGUE
ALTER TABLE nex.colleague OWNER TO nex;
GRANT ALL ON nex.colleague TO nex;
REVOKE ALL ON nex.colleague FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.colleague TO curator;
GRANT SELECT ON nex.colleague TO PUBLIC;

-- Set privilege on TABLE COLLEAGUETRIAGE
ALTER TABLE nex.colleaguetriage OWNER TO nex;
GRANT ALL ON nex.colleaguetriage TO nex;
REVOKE ALL ON nex.colleaguetriage FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.colleaguetriage TO curator;
GRANT SELECT ON nex.colleaguetriage TO PUBLIC;

-- Set privilege on TABLE COLLEAGUE_RELATION
ALTER TABLE nex.colleague_relation OWNER TO nex;
GRANT ALL ON nex.colleague_relation TO nex;
REVOKE ALL ON nex.colleague_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.colleague_relation TO curator;
GRANT SELECT ON nex.colleague_relation TO PUBLIC;

-- Set privilege on TABLE COLLEAGUE_KEYWORD
ALTER TABLE nex.colleague_keyword OWNER TO nex;
GRANT ALL ON nex.colleague_keyword TO nex;
REVOKE ALL ON nex.colleague_keyword FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.colleague_keyword TO curator;
GRANT SELECT ON nex.colleague_keyword TO PUBLIC;

-- Set privilege on TABLE COLLEAGUE_LOCUS
ALTER TABLE nex.colleague_locus OWNER TO nex;
GRANT ALL ON nex.colleague_locus TO nex;
REVOKE ALL ON nex.colleague_locus FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.colleague_locus TO curator;
GRANT SELECT ON nex.colleague_locus TO PUBLIC;

-- Set privilege on TABLE COLLEAGUE_REFERENCE
ALTER TABLE nex.colleague_reference OWNER TO nex;
GRANT ALL ON nex.colleague_reference TO nex;
REVOKE ALL ON nex.colleague_reference FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.colleague_reference TO curator;
GRANT SELECT ON nex.colleague_reference TO PUBLIC;

-- Set privilege on TABLE COLLEAGUE_URL
ALTER TABLE nex.colleague_url OWNER TO nex;
GRANT ALL ON nex.colleague_url TO nex;
REVOKE ALL ON nex.colleague_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.colleague_url TO curator;
GRANT SELECT ON nex.colleague_url TO PUBLIC;

-- Set privilege on TABLE CONTIG
ALTER TABLE nex.contig OWNER TO nex;
GRANT ALL ON nex.contig TO nex;
REVOKE ALL ON nex.contig FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.contig TO curator;
GRANT SELECT ON nex.contig TO PUBLIC;

-- Set privilege on TABLE CONTIGNOTEANNOTATION
ALTER TABLE nex.contignoteannotation OWNER TO nex;
GRANT ALL ON nex.contignoteannotation TO nex;
REVOKE ALL ON nex.contignoteannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.contignoteannotation TO curator;
GRANT SELECT ON nex.contignoteannotation TO PUBLIC;

-- Set privilege on TABLE CONTIG_URL
ALTER TABLE nex.contig_url OWNER TO nex;
GRANT ALL ON nex.contig_url TO nex;
REVOKE ALL ON nex.contig_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.contig_url TO curator;
GRANT SELECT ON nex.contig_url TO PUBLIC;

-- Set privilege on TABLE CURATION_LOCUS
ALTER TABLE nex.curation_locus OWNER TO nex;
GRANT ALL ON nex.curation_locus TO nex;
REVOKE ALL ON nex.curation_locus FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.curation_locus TO curator;
GRANT SELECT ON nex.curation_locus TO PUBLIC;

-- Set privilege on TABLE CURATION_REFERENCE                                                                                                                                                                    
ALTER TABLE nex.curation_reference OWNER TO nex;
GRANT ALL ON nex.curation_reference TO nex;
REVOKE ALL ON nex.curation_reference FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.curation_reference TO curator;
GRANT SELECT ON nex.curation_reference TO PUBLIC;

-- Set privilege on TABLE DATASET
ALTER TABLE nex.dataset OWNER TO nex;
GRANT ALL ON nex.dataset TO nex;
REVOKE ALL ON nex.dataset FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.dataset TO curator;
GRANT SELECT ON nex.dataset TO PUBLIC;

-- Set privilege on TABLE DATASETLAB
ALTER TABLE nex.datasetlab OWNER TO nex;
GRANT ALL ON nex.datasetlab TO nex;
REVOKE ALL ON nex.datasetlab FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.datasetlab TO curator;
GRANT SELECT ON nex.datasetlab TO PUBLIC;

-- Set privilege on TABLE DATASETSAMPLE
ALTER TABLE nex.datasetsample OWNER TO nex;
GRANT ALL ON nex.datasetsample TO nex;
REVOKE ALL ON nex.datasetsample FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.datasetsample TO curator;
GRANT SELECT ON nex.datasetsample TO PUBLIC;

-- Set privilege on TABLE DATASETTRACK
ALTER TABLE nex.datasettrack OWNER TO nex;
GRANT ALL ON nex.datasettrack TO nex;
REVOKE ALL ON nex.datasettrack FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.datasettrack TO curator;
GRANT SELECT ON nex.datasettrack TO PUBLIC;

-- Set privilege on TABLE DATASET_FILE
ALTER TABLE nex.dataset_file OWNER TO nex;
GRANT ALL ON nex.dataset_file TO nex;
REVOKE ALL ON nex.dataset_file FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.dataset_file TO curator;
GRANT SELECT ON nex.dataset_file TO PUBLIC;

-- Set privilege on TABLE DATASET_KEYWORD
ALTER TABLE nex.dataset_keyword OWNER TO nex;
GRANT ALL ON nex.dataset_keyword TO nex;
REVOKE ALL ON nex.dataset_keyword FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.dataset_keyword TO curator;
GRANT SELECT ON nex.dataset_keyword TO PUBLIC;

-- Set privilege on TABLE DATASET_REFERENCE
ALTER TABLE nex.dataset_reference OWNER TO nex;
GRANT ALL ON nex.dataset_reference TO nex;
REVOKE ALL ON nex.dataset_reference FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.dataset_reference TO curator;
GRANT SELECT ON nex.dataset_reference TO PUBLIC;

-- Set privilege on TABLE DATASET_URL
ALTER TABLE nex.dataset_url OWNER TO nex;
GRANT ALL ON nex.dataset_url TO nex;
REVOKE ALL ON nex.dataset_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.dataset_url TO curator;
GRANT SELECT ON nex.dataset_url TO PUBLIC;

-- Set privilege on TABLE DBENTITY
ALTER TABLE nex.dbentity OWNER TO nex;
GRANT ALL ON nex.dbentity TO nex;
REVOKE ALL ON nex.dbentity FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.dbentity TO curator;
GRANT SELECT ON nex.dbentity TO PUBLIC;

-- Set privilege on TABLE DBUSER
ALTER TABLE nex.dbuser OWNER TO nex;
GRANT ALL ON nex.dbuser TO nex;
REVOKE ALL ON nex.dbuser FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE ON nex.dbuser TO curator;
GRANT SELECT ON nex.dbuser TO PUBLIC;

-- Set privilege on TABLE DELETELOG
ALTER TABLE nex.deletelog OWNER TO nex;
GRANT ALL ON nex.deletelog TO nex;
REVOKE ALL ON nex.deletelog FROM PUBLIC;
GRANT SELECT,INSERT ON nex.deletelog TO curator;
GRANT SELECT ON nex.deletelog TO PUBLIC;

-- Set privilege on TABLE DNASEQUENCEANNOTATION
ALTER TABLE nex.dnasequenceannotation OWNER TO nex;
GRANT ALL ON nex.dnasequenceannotation TO nex;
REVOKE ALL ON nex.dnasequenceannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.dnasequenceannotation TO curator;
GRANT SELECT ON nex.dnasequenceannotation TO PUBLIC;

-- Set privilege on TABLE DNASUBSEQUENCE
ALTER TABLE nex.dnasubsequence OWNER TO nex;
GRANT ALL ON nex.dnasubsequence TO nex;
REVOKE ALL ON nex.dnasubsequence FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.dnasubsequence TO curator;
GRANT SELECT ON nex.dnasubsequence TO PUBLIC;

-- Set privilege on TABLE DISEASE
ALTER TABLE nex.disease OWNER TO nex;
GRANT ALL ON nex.disease TO nex;
REVOKE ALL ON nex.disease FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.disease TO curator;
GRANT SELECT ON nex.disease TO PUBLIC;

-- Set privilege on TABLE DISEASEANNOTATION
ALTER TAble diseaseannotation OWNER TO nex;
GRANT ALL ON nex.diseaseannotation TO nex;
REVOKE ALL ON nex.diseaseannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.diseaseannotation TO curator;
GRANT SELECT ON nex.diseaseannotation TO PUBLIC;

-- Set privilege on TABLE DISEASESUBSET
ALTER TABLE nex.diseasesubset OWNER TO nex;
GRANT ALL ON nex.diseasesubset TO nex;
REVOKE ALL ON nex.diseasesubset FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.diseasesubset TO curator;
GRANT SELECT ON nex.diseasesubset TO PUBLIC;

-- Set privilege on TABLE DISEASESUBSETANNOTATION
ALTER TABLE nex.diseasesubsetannotation OWNER TO nex;
GRANT ALL ON nex.diseasesubsetannotation TO nex;
REVOKE ALL ON nex.diseasesubsetannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.diseasesubsetannotation TO curator;
GRANT SELECT ON nex.diseasesubsetannotation TO PUBLIC;

-- Set privilege on TABLE DISEASESUPPORTINGEVIDENCE
ALTER TABLE nex.diseasesupportingevidence OWNER TO nex;
GRANT ALL ON nex.diseasesupportingevidence TO nex;
REVOKE ALL ON nex.diseasesupportingevidence FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.diseasesupportingevidence TO curator;
GRANT SELECT ON nex.diseasesupportingevidence TO PUBLIC;

-- Set privilege on TABLE DISEASE_ALIAS
ALTER TABLE nex.disease_alias OWNER TO nex;
GRANT ALL ON nex.disease_alias TO nex;
REVOKE ALL ON nex.disease_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.disease_alias TO curator;
GRANT SELECT ON nex.disease_alias TO PUBLIC;

-- Set privilege on TABLE DISEASE_RELATION
ALTER TABLE nex.disease_relation OWNER TO nex;
GRANT ALL ON nex.disease_relation TO nex;
REVOKE ALL ON nex.disease_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.disease_relation TO curator;
GRANT SELECT ON nex.disease_relation TO PUBLIC;

-- Set privilege on TABLE DISEASE_URL
ALTER TABLE nex.disease_url OWNER TO nex;
GRANT ALL ON nex.disease_url TO nex;
REVOKE ALL ON nex.disease_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.disease_url TO curator;
GRANT SELECT ON nex.disease_url TO PUBLIC;

-- Set privilege on TABLE EC
ALTER TABLE nex.ec OWNER TO nex;
GRANT ALL ON nex.ec TO nex;
REVOKE ALL ON nex.ec FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.ec TO curator;
GRANT SELECT ON nex.ec TO PUBLIC;

-- Set privilege on TABLE ECO
ALTER TABLE nex.eco OWNER TO nex;
GRANT ALL ON nex.eco TO nex;
REVOKE ALL ON nex.eco FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.eco TO curator;
GRANT SELECT ON nex.eco TO PUBLIC;

-- Set privilege on TABLE ECO_ALIAS
ALTER TABLE nex.eco_alias OWNER TO nex;
GRANT ALL ON nex.eco_alias TO nex;
REVOKE ALL ON nex.eco_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.eco_alias TO curator;
GRANT SELECT ON nex.eco_alias TO PUBLIC;

-- Set privilege on TABLE ECO_RELATION
ALTER TABLE nex.eco_relation OWNER TO nex;
GRANT ALL ON nex.eco_relation TO nex;
REVOKE ALL ON nex.eco_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.eco_relation TO curator;
GRANT SELECT ON nex.eco_relation TO PUBLIC;

-- Set privilege on TABLE ECO_URL
ALTER TABLE nex.eco_url OWNER TO nex;
GRANT ALL ON nex.eco_url TO nex;
REVOKE ALL ON nex.eco_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.eco_url TO curator;
GRANT SELECT ON nex.eco_url TO PUBLIC;

-- Set privilege on TABLE EC_ALIAS
ALTER TABLE nex.ec_alias OWNER TO nex;
GRANT ALL ON nex.ec_alias TO nex;
REVOKE ALL ON nex.ec_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.ec_alias TO curator;
GRANT SELECT ON nex.ec_alias TO PUBLIC;

-- Set privilege on TABLE EC_URL
ALTER TABLE nex.ec_url OWNER TO nex;
GRANT ALL ON nex.ec_url TO nex;
REVOKE ALL ON nex.ec_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.ec_url TO curator;
GRANT SELECT ON nex.ec_url TO PUBLIC;

-- Set privilege on TABLE EDAM
ALTER TABLE nex.edam OWNER TO nex;
GRANT ALL ON nex.edam TO nex;
REVOKE ALL ON nex.edam FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.edam TO curator;
GRANT SELECT ON nex.edam TO PUBLIC;

-- Set privilege on TABLE EDAM_ALIAS
ALTER TABLE nex.edam_alias OWNER TO nex;
GRANT ALL ON nex.edam_alias TO nex;
REVOKE ALL ON nex.edam_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.edam_alias TO curator;
GRANT SELECT ON nex.edam_alias TO PUBLIC;

-- Set privilege on TABLE EDAM_RELATION
ALTER TABLE nex.edam_relation OWNER TO nex;
GRANT ALL ON nex.edam_relation TO nex;
REVOKE ALL ON nex.edam_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.edam_relation TO curator;
GRANT SELECT ON nex.edam_relation TO PUBLIC;

-- Set privilege on TABLE EDAM_URL
ALTER TABLE nex.edam_url OWNER TO nex;
GRANT ALL ON nex.edam_url TO nex;
REVOKE ALL ON nex.edam_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.edam_url TO curator;
GRANT SELECT ON nex.edam_url TO PUBLIC;

-- Set privilege on TABLE ENZYMEANNOTATION
ALTER TABLE nex.enzymeannotation OWNER TO nex;
GRANT ALL ON nex.enzymeannotation TO nex;
REVOKE ALL ON nex.enzymeannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.enzymeannotation TO curator;
GRANT SELECT ON nex.enzymeannotation TO PUBLIC;

-- Set privilege on TABLE EXPRESSIONANNOTATION
ALTER TABLE nex.expressionannotation OWNER TO nex;
GRANT ALL ON nex.expressionannotation TO nex;
REVOKE ALL ON nex.expressionannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.expressionannotation TO curator;
GRANT SELECT ON nex.expressionannotation TO PUBLIC;

-- Set privilege on TABLE FILEDBENTITY
ALTER TABLE nex.filedbentity OWNER TO nex;
GRANT ALL ON nex.filedbentity TO nex;
REVOKE ALL ON nex.filedbentity FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.filedbentity TO curator;
GRANT SELECT ON nex.filedbentity TO PUBLIC;

-- Set privilege on TABLE FILEPATH
ALTER TABLE nex.filepath OWNER TO nex;
GRANT ALL ON nex.filepath TO nex;
REVOKE ALL ON nex.filepath FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.filepath TO curator;
GRANT SELECT ON nex.filepath TO PUBLIC;

-- Set privilege on TABLE FILE_KEYWORD
ALTER TABLE nex.file_keyword OWNER TO nex;
GRANT ALL ON nex.file_keyword TO nex;
REVOKE ALL ON nex.file_keyword FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.file_keyword TO curator;
GRANT SELECT ON nex.file_keyword TO PUBLIC;

-- Set privilege on TABLE GENINTERACTIONANNOTATION
ALTER TABLE nex.geninteractionannotation OWNER TO nex;
GRANT ALL ON nex.geninteractionannotation TO nex;
REVOKE ALL ON nex.geninteractionannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.geninteractionannotation TO curator;
GRANT SELECT ON nex.geninteractionannotation TO PUBLIC;

-- Set privilege on TABLE GENOMERELEASE
ALTER TABLE nex.genomerelease OWNER TO nex;
GRANT ALL ON nex.genomerelease TO nex;
REVOKE ALL ON nex.genomerelease FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.genomerelease TO curator;
GRANT SELECT ON nex.genomerelease TO PUBLIC;

-- Set privilege on TABLE GO
ALTER TABLE nex.go OWNER TO nex;
GRANT ALL ON nex.go TO nex;
REVOKE ALL ON nex.go FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.go TO curator;
GRANT SELECT ON nex.go TO PUBLIC;

-- Set privilege on TABLE GOANNOTATION
ALTER TABLE nex.goannotation OWNER TO nex;
GRANT ALL ON nex.goannotation TO nex;
REVOKE ALL ON nex.goannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.goannotation TO curator;
GRANT SELECT ON nex.goannotation TO PUBLIC;

-- Set privilege on TABLE GOEXTENSION
ALTER TABLE nex.goextension OWNER TO nex;
GRANT ALL ON nex.goextension TO nex;
REVOKE ALL ON nex.goextension FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.goextension TO curator;
GRANT SELECT ON nex.goextension TO PUBLIC;

-- Set privilege on TABLE GOSLIM
ALTER TABLE nex.goslim OWNER TO nex;
GRANT ALL ON nex.goslim TO nex;
REVOKE ALL ON nex.goslim FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.goslim TO curator;
GRANT SELECT ON nex.goslim TO PUBLIC;

-- Set privilege on TABLE GOSLIMANNOTATION
ALTER TABLE nex.goslimannotation OWNER TO nex;
GRANT ALL ON nex.goslimannotation TO nex;
REVOKE ALL ON nex.goslimannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.goslimannotation TO curator;
GRANT SELECT ON nex.goslimannotation TO PUBLIC;

-- Set privilege on TABLE GOSUPPORTINGEVIDENCE
ALTER TABLE nex.gosupportingevidence OWNER TO nex;
GRANT ALL ON nex.gosupportingevidence TO nex;
REVOKE ALL ON nex.gosupportingevidence FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.gosupportingevidence TO curator;
GRANT SELECT ON nex.gosupportingevidence TO PUBLIC;

-- Set privilege on TABLE GO_ALIAS
ALTER TABLE nex.go_alias OWNER TO nex;
GRANT ALL ON nex.go_alias TO nex;
REVOKE ALL ON nex.go_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.go_alias TO curator;
GRANT SELECT ON nex.go_alias TO PUBLIC;

-- Set privilege on TABLE GO_RELATION
ALTER TABLE nex.go_relation OWNER TO nex;
GRANT ALL ON nex.go_relation TO nex;
REVOKE ALL ON nex.go_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.go_relation TO curator;
GRANT SELECT ON nex.go_relation TO PUBLIC;

-- Set privilege on TABLE GO_URL
ALTER TABLE nex.go_url OWNER TO nex;
GRANT ALL ON nex.go_url TO nex;
REVOKE ALL ON nex.go_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.go_url TO curator;
GRANT SELECT ON nex.go_url TO PUBLIC;

-- Set privilege on TABLE JOURNAL
ALTER TABLE nex.journal OWNER TO nex;
GRANT ALL ON nex.journal TO nex;
REVOKE ALL ON nex.journal FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.journal TO curator;
GRANT SELECT ON nex.journal TO PUBLIC;

-- Set privilege on TABLE KEYWORD
ALTER TABLE nex.keyword OWNER TO nex;
GRANT ALL ON nex.keyword TO nex;
REVOKE ALL ON nex.keyword FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.keyword TO curator;
GRANT SELECT ON nex.keyword TO PUBLIC;

-- Set privilege on TABLE LITERATUREANNOTATION
ALTER TABLE nex.literatureannotation OWNER TO nex;
GRANT ALL ON nex.literatureannotation TO nex;
REVOKE ALL ON nex.literatureannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.literatureannotation TO curator;
GRANT SELECT ON nex.literatureannotation TO PUBLIC;

-- Set privilege on TABLE LOCUSDBENTITY
ALTER TABLE nex.locusdbentity OWNER TO nex;
GRANT ALL ON nex.locusdbentity TO nex;
REVOKE ALL ON nex.locusdbentity FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locusdbentity TO curator;
GRANT SELECT ON nex.locusdbentity TO PUBLIC;

-- Set privilege on TABLE LOCUS_REFERENCE
ALTER TABLE nex.locus_reference OWNER TO nex;
GRANT ALL ON nex.locus_reference TO nex;
REVOKE ALL ON nex.locus_reference FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locus_reference TO curator;
GRANT SELECT ON nex.locus_reference TO PUBLIC;

-- Set privilege on TABLE LOCUSNOTEANNOTATION
ALTER TABLE nex.locusnoteannotation OWNER TO nex;
GRANT ALL ON nex.locusnoteannotation TO nex;
REVOKE ALL ON nex.locusnoteannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locusnoteannotation TO curator;
GRANT SELECT ON nex.locusnoteannotation TO PUBLIC;

-- Set privilege on TABLE LOCUS_ALIAS
ALTER TABLE nex.locus_alias OWNER TO nex;
GRANT ALL ON nex.locus_alias TO nex;
REVOKE ALL ON nex.locus_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locus_alias TO curator;
GRANT SELECT ON nex.locus_alias TO PUBLIC;

-- Set privilege on TABLE LOCUSALIAS_REFERENCE
 ALTER TABLE nex.locusalias_reference OWNER TO nex;
GRANT ALL ON nex.locusalias_reference TO nex;
REVOKE ALL ON nex.locusalias_reference FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locusalias_reference TO curator;
GRANT SELECT ON nex.locusalias_reference TO PUBLIC;

-- Set privilege on TABLE LOCUS_RELATION
ALTER TABLE nex.locus_relation OWNER TO nex;
GRANT ALL ON nex.locus_relation TO nex;
REVOKE ALL ON nex.locus_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locus_relation TO curator;
GRANT SELECT ON nex.locus_relation TO PUBLIC;

-- Set privilege on TABLE LOCUSSUMMARY
ALTER TABLE nex.locussummary OWNER TO nex;
GRANT ALL ON nex.locussummary TO nex;
REVOKE ALL ON nex.locussummary FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locussummary TO curator;
GRANT SELECT ON nex.locussummary TO PUBLIC;

-- Set privilege on TABLE LOCUSSUMMARY_REFERENCE
ALTER TABLE nex.locussummary_reference OWNER TO nex;
GRANT ALL ON nex.locussummary_reference TO nex;
REVOKE ALL ON nex.locussummary_reference FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locussummary_reference TO curator;
GRANT SELECT ON nex.locussummary_reference TO PUBLIC;

-- Set privilege on TABLE LOCUS_URL
ALTER TABLE nex.locus_url OWNER TO nex;
GRANT ALL ON nex.locus_url TO nex;
REVOKE ALL ON nex.locus_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.locus_url TO curator;
GRANT SELECT ON nex.locus_url TO PUBLIC;

-- Set privilege on TABLE OBI
ALTER TABLE nex.obi OWNER TO nex;
GRANT ALL ON nex.obi TO nex;
REVOKE ALL ON nex.obi FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.obi TO curator;
GRANT SELECT ON nex.obi TO PUBLIC;

-- Set privilege on TABLE OBI_RELATION
ALTER TABLE nex.obi_relation OWNER TO nex;
GRANT ALL ON nex.obi_relation TO nex;
REVOKE ALL ON nex.obi_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.obi_relation TO curator;
GRANT SELECT ON nex.obi_relation TO PUBLIC;

-- Set privilege on TABLE OBI_URL
ALTER TABLE nex.obi_url OWNER TO nex;
GRANT ALL ON nex.obi_url TO nex;
REVOKE ALL ON nex.obi_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.obi_url TO curator;
GRANT SELECT ON nex.obi_url TO PUBLIC;

-- Set privilege on TABLE PATHWAYANNOTATION
ALTER TABLE nex.pathwayannotation OWNER TO nex;
GRANT ALL ON nex.pathwayannotation TO nex;
REVOKE ALL ON nex.pathwayannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.pathwayannotation TO curator;
GRANT SELECT ON nex.pathwayannotation TO PUBLIC;

-- Set privilege on TABLE PATHWAYDBENTITY
ALTER TABLE nex.pathwaydbentity OWNER TO nex;
GRANT ALL ON nex.pathwaydbentity TO nex;
REVOKE ALL ON nex.pathwaydbentity FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.pathwaydbentity TO curator;
GRANT SELECT ON nex.pathwaydbentity TO PUBLIC;

-- Set privilege on TABLE PATHWAY_ALIAS
ALTER TABLE nex.pathway_alias OWNER TO nex;
GRANT ALL ON nex.pathway_alias TO nex;
REVOKE ALL ON nex.pathway_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.pathway_alias TO curator;
GRANT SELECT ON nex.pathway_alias TO PUBLIC;

-- Set privilege on TABLE PATHWAYSUMMARY
ALTER TABLE nex.pathwaysummary OWNER TO nex;
GRANT ALL ON nex.pathwaysummary TO nex;
REVOKE ALL ON nex.pathwaysummary FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.pathwaysummary TO curator;
GRANT SELECT ON nex.pathwaysummary TO PUBLIC;

-- Set privilege on TABLE PATHWAYSUMMARY_REFERENCE
ALTER TABLE nex.pathwaysummary_reference OWNER TO nex;
GRANT ALL ON nex.pathwaysummary_reference TO nex;
REVOKE ALL ON nex.pathwaysummary_reference FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.pathwaysummary_reference TO curator;
GRANT SELECT ON nex.pathwaysummary_reference TO PUBLIC;

-- Set privilege on TABLE PATHWAY_URL
ALTER TABLE nex.pathway_url OWNER TO nex;
GRANT ALL ON nex.pathway_url TO nex;
REVOKE ALL ON nex.pathway_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.pathway_url TO curator;
GRANT SELECT ON nex.pathway_url TO PUBLIC;

-- Set privilege on TABLE PHENOTYPE
ALTER TABLE nex.phenotype OWNER TO nex;
GRANT ALL ON nex.phenotype TO nex;
REVOKE ALL ON nex.phenotype FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.phenotype TO curator;
GRANT SELECT ON nex.phenotype TO PUBLIC;

-- Set privilege on TABLE PHENOTYPEANNOTATION
ALTER TABLE nex.phenotypeannotation OWNER TO nex;
GRANT ALL ON nex.phenotypeannotation TO nex;
REVOKE ALL ON nex.phenotypeannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.phenotypeannotation TO curator;
GRANT SELECT ON nex.phenotypeannotation TO PUBLIC;

-- Set privilege on TABLE PHENOTYPEANNOTATION_COND
ALTER TABLE nex.phenotypeannotation_cond OWNER TO nex;
GRANT ALL ON nex.phenotypeannotation_cond TO nex;
REVOKE ALL ON nex.phenotypeannotation_cond FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.phenotypeannotation_cond TO curator;
GRANT SELECT ON nex.phenotypeannotation_cond TO PUBLIC;

-- Set privilege on TABLE PHYSINTERACTIONANNOTATION
ALTER TABLE nex.physinteractionannotation OWNER TO nex;
GRANT ALL ON nex.physinteractionannotation TO nex;
REVOKE ALL ON nex.physinteractionannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.physinteractionannotation TO curator;
GRANT SELECT ON nex.physinteractionannotation TO PUBLIC;

-- Set privilege on TABLE POSTTRANSLATIONANNOTATION
ALTER TABLE nex.posttranslationannotation OWNER TO nex;
GRANT ALL ON nex.posttranslationannotation TO nex;
REVOKE ALL ON nex.posttranslationannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.posttranslationannotation TO curator;
GRANT SELECT ON nex.posttranslationannotation TO PUBLIC;

-- Set privilege on TABLE PROTEINDOMAIN
ALTER TABLE nex.proteindomain OWNER TO nex;
GRANT ALL ON nex.proteindomain TO nex;
REVOKE ALL ON nex.proteindomain FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.proteindomain TO curator;
GRANT SELECT ON nex.proteindomain TO PUBLIC;

-- Set privilege on TABLE PROTEINDOMAINANNOTATION
ALTER TABLE nex.proteindomainannotation OWNER TO nex;
GRANT ALL ON nex.proteindomainannotation TO nex;
REVOKE ALL ON nex.proteindomainannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.proteindomainannotation TO curator;
GRANT SELECT ON nex.proteindomainannotation TO PUBLIC;

-- Set privilege on TABLE PROTEINDOMAIN_URL
ALTER TABLE nex.proteindomain_url OWNER TO nex;
GRANT ALL ON nex.proteindomain_url TO nex;
REVOKE ALL ON nex.proteindomain_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.proteindomain_url TO curator;
GRANT SELECT ON nex.proteindomain_url TO PUBLIC;

-- Set privilege on TABLE PROTEINEXPTANNOTATION
ALTER TABLE nex.proteinexptannotation OWNER TO nex;
GRANT ALL ON nex.proteinexptannotation TO nex;
REVOKE ALL ON nex.proteinexptannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.proteinexptannotation TO curator;
GRANT SELECT ON nex.proteinexptannotation TO PUBLIC;

-- Set privilege on TABLE PROTEINEXPTANNOTATION_COND
ALTER TABLE nex.proteinexptannotation_cond OWNER TO nex;
GRANT ALL ON nex.proteinexptannotation_cond TO nex;
REVOKE ALL ON nex.proteinexptannotation_cond FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.proteinexptannotation_cond TO curator;
GRANT SELECT ON nex.proteinexptannotation_cond TO PUBLIC;

-- Set privilege on TABLE PROTEINSEQUENCEANNOTATION
ALTER TABLE nex.proteinsequenceannotation OWNER TO nex;
GRANT ALL ON nex.proteinsequenceannotation TO nex;
REVOKE ALL ON nex.proteinsequenceannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.proteinsequenceannotation TO curator;
GRANT SELECT ON nex.proteinsequenceannotation TO PUBLIC;

-- Set privilege on TABLE PROTEINSEQUENCE_DETAIL
ALTER TABLE nex.proteinsequence_detail OWNER TO nex;
GRANT ALL ON nex.proteinsequence_detail TO nex;
REVOKE ALL ON nex.proteinsequence_detail FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.proteinsequence_detail TO curator;
GRANT SELECT ON nex.proteinsequence_detail TO PUBLIC;

-- Set privilege on TABLE PSIMOD
ALTER TABLE nex.psimod OWNER TO nex;
GRANT ALL ON nex.psimod TO nex;
REVOKE ALL ON nex.psimod FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.psimod TO curator;
GRANT SELECT ON nex.psimod TO PUBLIC;

-- Set privilege on TABLE PSIMOD_RELATION
ALTER TABLE nex.psimod_relation OWNER TO nex;
GRANT ALL ON nex.psimod_relation TO nex;
REVOKE ALL ON nex.psimod_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.psimod_relation TO curator;
GRANT SELECT ON nex.psimod_relation TO PUBLIC;

-- Set privilege on TABLE PSIMOD_URL
ALTER TABLE nex.psimod_url OWNER TO nex;
GRANT ALL ON nex.psimod_url TO nex;
REVOKE ALL ON nex.psimod_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.psimod_url TO curator;
GRANT SELECT ON nex.psimod_url TO PUBLIC;

-- Set privilege on TABLE REFERENCEDBENTITY
ALTER TABLE nex.referencedbentity OWNER TO nex;
GRANT ALL ON nex.referencedbentity TO nex;
REVOKE ALL ON nex.referencedbentity FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.referencedbentity TO curator;
GRANT SELECT ON nex.referencedbentity TO PUBLIC;

-- Set privilege on TABLE REFERENCETRIAGE
ALTER TABLE nex.referencetriage OWNER TO nex;
GRANT ALL ON nex.referencetriage TO nex;
REVOKE ALL ON nex.referencetriage FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.referencetriage TO curator;
GRANT SELECT ON nex.referencetriage TO PUBLIC;

-- Set privilege on TABLE REFERENCE_ALIAS
ALTER TABLE nex.reference_alias OWNER TO nex;
GRANT ALL ON nex.reference_alias TO nex;
REVOKE ALL ON nex.reference_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.reference_alias TO curator;
GRANT SELECT ON nex.reference_alias TO PUBLIC;

-- Set privilege on TABLE REFERENCEAUTHOR
ALTER TABLE nex.referenceauthor OWNER TO nex;
GRANT ALL ON nex.referenceauthor TO nex;
REVOKE ALL ON nex.referenceauthor FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.referenceauthor TO curator;
GRANT SELECT ON nex.referenceauthor TO PUBLIC;

-- Set privilege on TABLE REFERENCE_RELATION
ALTER TABLE nex.reference_relation OWNER TO nex;
GRANT ALL ON nex.reference_relation TO nex;
REVOKE ALL ON nex.reference_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.reference_relation TO curator;
GRANT SELECT ON nex.reference_relation TO PUBLIC;

-- Set privilege on TABLE REFERENCEDELETED
ALTER TABLE nex.referencedeleted OWNER TO nex;
GRANT ALL ON nex.referencedeleted TO nex;
REVOKE ALL ON nex.referencedeleted FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.referencedeleted TO curator;
GRANT SELECT ON nex.referencedeleted TO PUBLIC;

-- Set privilege on TABLE REFERENCEDOCUMENT
ALTER TABLE nex.referencedocument OWNER TO nex;
GRANT ALL ON nex.referencedocument TO nex;
REVOKE ALL ON nex.referencedocument FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.referencedocument TO curator;
GRANT SELECT ON nex.referencedocument TO PUBLIC;

-- Set privilege on TABLE REFERENCE_FILE
ALTER TABLE nex.reference_file OWNER TO nex;
GRANT ALL ON nex.reference_file TO nex;
REVOKE ALL ON nex.reference_file FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.reference_file TO curator;
GRANT SELECT ON nex.reference_file TO PUBLIC;

-- Set privilege on TABLE REFERENCETYPE
ALTER TABLE nex.referencetype OWNER TO nex;
GRANT ALL ON nex.referencetype TO nex;
REVOKE ALL ON nex.referencetype FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.referencetype TO curator;
GRANT SELECT ON nex.referencetype TO PUBLIC;

-- Set privilege on TABLE REFERENCEUNLINK
ALTER TABLE nex.referenceunlink OWNER TO nex;
GRANT ALL ON nex.referenceunlink TO nex;
REVOKE ALL ON nex.referenceunlink FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.referenceunlink TO curator;
GRANT SELECT ON nex.referenceunlink TO PUBLIC;

-- Set privilege on TABLE REFERENCE_URL
ALTER TABLE nex.reference_url OWNER TO nex;
GRANT ALL ON nex.reference_url TO nex;
REVOKE ALL ON nex.reference_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.reference_url TO curator;
GRANT SELECT ON nex.reference_url TO PUBLIC;

-- Set privilege on TABLE REGULATIONANNOTATION  
ALTER TABLE nex.regulationannotation OWNER TO nex;
GRANT ALL ON nex.regulationannotation TO nex;
REVOKE ALL ON nex.regulationannotation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.regulationannotation TO curator;
GRANT SELECT ON nex.regulationannotation TO PUBLIC;

-- Set privilege on TABLE REPORTER
ALTER TABLE nex.reporter OWNER TO nex;
GRANT ALL ON nex.reporter TO nex;
REVOKE ALL ON nex.reporter FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.reporter TO curator;
GRANT SELECT ON nex.reporter TO PUBLIC;

-- Set privilege on TABLE RESERVEDNAME
ALTER TABLE nex.reservedname OWNER TO nex;
GRANT ALL ON nex.reservedname TO nex;
REVOKE ALL ON nex.reservedname FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.reservedname TO curator;
GRANT SELECT ON nex.reservedname TO PUBLIC;

-- Set privilege on TABLE RO
ALTER TABLE nex.ro OWNER TO nex;
GRANT ALL ON nex.ro TO nex;
REVOKE ALL ON nex.ro FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.ro TO curator;
GRANT SELECT ON nex.ro TO PUBLIC;

-- Set privilege on TABLE RO_RELATION
ALTER TABLE nex.ro_relation OWNER TO nex;
GRANT ALL ON nex.ro_relation TO nex;
REVOKE ALL ON nex.ro_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.ro_relation TO curator;
GRANT SELECT ON nex.ro_relation TO PUBLIC;

-- Set privilege on TABLE RO_URL
ALTER TABLE nex.ro_url OWNER TO nex;
GRANT ALL ON nex.ro_url TO nex;
REVOKE ALL ON nex.ro_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.ro_url TO curator;
GRANT SELECT ON nex.ro_url TO PUBLIC;

-- Set privilege on TABLE SGDID
ALTER TABLE nex.sgdid OWNER TO nex;
GRANT ALL ON nex.sgdid TO nex;
REVOKE ALL ON nex.sgdid FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE ON nex.sgdid TO curator;
GRANT SELECT ON nex.sgdid TO PUBLIC;

-- Set privilege on TABLE SO
ALTER TABLE nex.so OWNER TO nex;
GRANT ALL ON nex.so TO nex;
REVOKE ALL ON nex.so FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.so TO curator;
GRANT SELECT ON nex.so TO PUBLIC;

-- Set privilege on TABLE SOURCE
ALTER TABLE nex.source OWNER TO nex;
GRANT ALL ON nex.source TO nex;
REVOKE ALL ON nex.source FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.source TO curator;
GRANT SELECT ON nex.source TO PUBLIC;

-- Set privilege on TABLE SO_ALIAS
ALTER TABLE nex.so_alias OWNER TO nex;
GRANT ALL ON nex.so_alias TO nex;
REVOKE ALL ON nex.so_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.so_alias TO curator;
GRANT SELECT ON nex.so_alias TO PUBLIC;

-- Set privilege on TABLE SO_RELATION
ALTER TABLE nex.so_relation OWNER TO nex;
GRANT ALL ON nex.so_relation TO nex;
REVOKE ALL ON nex.so_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.so_relation TO curator;
GRANT SELECT ON nex.so_relation TO PUBLIC;

-- Set privilege on TABLE SO_URL
ALTER TABLE nex.so_url OWNER TO nex;
GRANT ALL ON nex.so_url TO nex;
REVOKE ALL ON nex.so_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.so_url TO curator;
GRANT SELECT ON nex.so_url TO PUBLIC;

-- Set privilege on TABLE STRAINDBENTITY
ALTER TABLE nex.straindbentity OWNER TO nex;
GRANT ALL ON nex.straindbentity TO nex;
REVOKE ALL ON nex.straindbentity FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.straindbentity TO curator;
GRANT SELECT ON nex.straindbentity TO PUBLIC;

-- Set privilege on TABLE STRAINSUMMARY
ALTER TABLE nex.strainsummary OWNER TO nex;
GRANT ALL ON nex.strainsummary TO nex;
REVOKE ALL ON nex.strainsummary FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.strainsummary TO curator;
GRANT SELECT ON nex.strainsummary TO PUBLIC;

-- Set privilege on TABLE STRAINSUMMARY_REFERENCE
ALTER TABLE nex.strainsummary_reference OWNER TO nex;
GRANT ALL ON nex.strainsummary_reference TO nex;
REVOKE ALL ON nex.strainsummary_reference FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.strainsummary_reference TO curator;
GRANT SELECT ON nex.strainsummary_reference TO PUBLIC;

-- Set privilege on TABLE STRAIN_URL
ALTER TABLE nex.strain_url OWNER TO nex;
GRANT ALL ON nex.strain_url TO nex;
REVOKE ALL ON nex.strain_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.strain_url TO curator;
GRANT SELECT ON nex.strain_url TO PUBLIC;

-- Set privilege on TABLE TAXONOMY
ALTER TABLE nex.taxonomy OWNER TO nex;
GRANT ALL ON nex.taxonomy TO nex;
REVOKE ALL ON nex.taxonomy FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.taxonomy TO curator;
GRANT SELECT ON nex.taxonomy TO PUBLIC;

-- Set privilege on TABLE TAXONOMY_ALIAS
ALTER TABLE nex.taxonomy_alias OWNER TO nex;
GRANT ALL ON nex.taxonomy_alias TO nex;
REVOKE ALL ON nex.taxonomy_alias FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.taxonomy_alias TO curator;
GRANT SELECT ON nex.taxonomy_alias TO PUBLIC;

-- Set privilege on TABLE TAXONOMY_RELATION
ALTER TABLE nex.taxonomy_relation OWNER TO nex;
GRANT ALL ON nex.taxonomy_relation TO nex;
REVOKE ALL ON nex.taxonomy_relation FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.taxonomy_relation TO curator;
GRANT SELECT ON nex.taxonomy_relation TO PUBLIC;

-- Set privilege on TABLE TAXONOMY_URL
ALTER TABLE nex.taxonomy_url OWNER TO nex;
GRANT ALL ON nex.taxonomy_url TO nex;
REVOKE ALL ON nex.taxonomy_url FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON nex.taxonomy_url TO curator;
GRANT SELECT ON nex.taxonomy_url TO PUBLIC;

-- Set privilege on TABLE UPDATELOG
ALTER TABLE nex.updatelog OWNER TO nex;
GRANT ALL ON nex.updatelog TO nex;
REVOKE ALL ON nex.updatelog FROM PUBLIC;
GRANT SELECT,INSERT ON nex.updatelog TO curator;
GRANT SELECT ON nex.updatelog TO PUBLIC;

-- Set privilege on SEQUENCES
grant select on all sequences in schema nex to curator;

-- Set privilege on FUNCTIONS
grant execute on all functions in schema nex to curator;
