-- Generated by Ora2Pg, the Oracle database Schema converter, version 17.4
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sgd-nex2-db.stanford.edu;sid=SGD

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

-- Audit & Basic tables

DROP TABLE IF EXISTS deletelog CASCADE;
CREATE TABLE deletelog (
	deletelog_id bigint NOT NULL DEFAULT nextval('deletelog_seq'),
	bud_id integer,
	tab_name varchar(60) NOT NULL,
	primary_key bigint NOT NULL,
	date_created timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	created_by varchar(12) NOT NULL,
	deleted_row text NOT NULL,
	CONSTRAINT deletelog_pk PRIMARY KEY (deletelog_id)
) ;
COMMENT ON TABLE deletelog IS 'Contains a copy of every deleted row, populated by triggers.';
COMMENT ON COLUMN deletelog.date_created IS 'Date the record was entered into the database.';
COMMENT ON COLUMN deletelog.primary_key IS 'Primary key of the row deleted.';
COMMENT ON COLUMN deletelog.tab_name IS 'Table name.';
COMMENT ON COLUMN deletelog.deletelog_id IS 'Unique identifier (serial number).';
COMMENT ON COLUMN deletelog.created_by IS 'Username of the person who entered the record into the database.';
COMMENT ON COLUMN deletelog.deleted_row IS 'Concatenation of all columns in the row deleted.';
COMMENT ON COLUMN deletelog.bud_id IS 'PK from BUD.DELETE_LOG.DELETE_LOG_NO.';

DROP TABLE IF EXISTS updatelog CASCADE; 
CREATE TABLE updatelog (
	updatelog_id bigint NOT NULL DEFAULT nextval('updatelog_seq'),
	bud_id integer,
	tab_name varchar(60) NOT NULL,
	col_name varchar(60) NOT NULL,
	primary_key bigint NOT NULL,
	date_created timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	created_by varchar(12) NOT NULL,
	old_value text,
	new_value text,
	CONSTRAINT updatelog_pk PRIMARY KEY (updatelog_id)
) ;
COMMENT ON TABLE updatelog IS 'Contains a copy of every updated column, populated by triggers.';
COMMENT ON COLUMN updatelog.date_created IS 'Date the record was entered into the database.';
COMMENT ON COLUMN updatelog.tab_name IS 'Name of the table updated.';
COMMENT ON COLUMN updatelog.updatelog_id IS 'Unique identifier (serial number).';
COMMENT ON COLUMN updatelog.new_value IS 'Column new value.';
COMMENT ON COLUMN updatelog.created_by IS 'Username of the person who entered the record into the database.';
COMMENT ON COLUMN updatelog.primary_key IS 'Primary key of the row that was updated.';
COMMENT ON COLUMN updatelog.col_name IS 'Name of the column updated.';
COMMENT ON COLUMN updatelog.old_value IS 'Column old value.';
COMMENT ON COLUMN updatelog.bud_id IS 'PK from BUD.UPDATE_LOG.UPDATE_LOG_NO.';

DROP TABLE IF EXISTS dbuser CASCADE; 
CREATE TABLE dbuser (
	dbuser_id bigint NOT NULL DEFAULT nextval('object_seq'),
	username varchar(12) NOT NULL,
	first_name varchar(40) NOT NULL,
	last_name varchar(40) NOT NULL,
	status varchar(40) NOT NULL,
	is_curator boolean NOT NULL,
	email varchar(100) NOT NULL,
	date_created timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	CONSTRAINT dbuser_pk PRIMARY KEY (dbuser_id)
) ;
COMMENT ON TABLE dbuser IS 'Current or former users with logins to the SGD database.';
COMMENT ON COLUMN dbuser.status IS 'Current state of the database user (Current, Former).';
COMMENT ON COLUMN dbuser.dbuser_id IS 'Unique identifier (serial number).';
COMMENT ON COLUMN dbuser.date_created IS 'Date the record was entered into the database.';
COMMENT ON COLUMN dbuser.last_name IS 'Last name of the database user.';
COMMENT ON COLUMN dbuser.first_name IS 'First name of the database user.';
COMMENT ON COLUMN dbuser.username IS 'Database login name.';
COMMENT ON COLUMN dbuser.email IS 'Stanford (SUNetID) email address of the database user.';
COMMENT ON COLUMN dbuser.is_curator IS 'Whether the user is a curator.';
ALTER TABLE dbuser ADD CONSTRAINT dbuser_uk UNIQUE (username);
ALTER TABLE dbuser ADD CONSTRAINT dbuser_status_ck CHECK (STATUS IN ('Current','Former'));

DROP TABLE IF EXISTS source CASCADE; 
CREATE TABLE source (
	source_id bigint NOT NULL DEFAULT nextval('object_seq'),
	format_name varchar(100) NOT NULL,
	display_name varchar(500) NOT NULL,
	bud_id integer,
	description varchar(500),
	date_created timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	created_by varchar(12) NOT NULL,
	CONSTRAINT source_pk PRIMARY KEY (source_id)
) ;
COMMENT ON TABLE source IS 'Origin or source of the data.';
COMMENT ON COLUMN source.created_by IS 'Username of the person who entered the record into the database.';
COMMENT ON COLUMN source.source_id IS 'Unique identifier (serial number).';
COMMENT ON COLUMN source.description IS 'Description or comment.';
COMMENT ON COLUMN source.date_created IS 'Date the record was entered into the database.';
COMMENT ON COLUMN source.display_name IS 'Public display name.';
COMMENT ON COLUMN source.bud_id IS 'PK from BUD.CODE.CODE_NO.';
COMMENT ON COLUMN source.format_name IS 'Unique name to create download files.';
ALTER TABLE source ADD CONSTRAINT source_uk UNIQUE (format_name);

DROP TABLE IF EXISTS sgdid CASCADE; 
CREATE TABLE sgdid (
	sgdid_id bigint NOT NULL DEFAULT nextval('object_seq'),
	format_name varchar(100) NOT NULL,
	display_name varchar(500) NOT NULL,
	obj_url varchar(500) NOT NULL,
	source_id bigint NOT NULL,
	bud_id integer,
	subclass varchar(40) NOT NULL,
	sgdid_status varchar(40) NOT NULL,
	description varchar(1000),
	date_created timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	created_by varchar(12) NOT NULL,
	CONSTRAINT sgdid_pk PRIMARY KEY (sgdid_id)
) ;
COMMENT ON TABLE sgdid IS 'SGD accession identifier for dbentity objects consisting of a letter (S or L) followed by 9 zero-padded numbers (e.g., S000151155).';
COMMENT ON COLUMN sgdid.obj_url IS 'URL of the object (relative for local links or complete for external links).';
COMMENT ON COLUMN sgdid.display_name IS 'Public display name.';
COMMENT ON COLUMN sgdid.bud_id IS 'PK from BUD.DBXREF.DBXREF_NO.';
COMMENT ON COLUMN sgdid.sgdid_id IS 'Unique identifier (serial number).';
COMMENT ON COLUMN sgdid.subclass IS 'Type of dbentity assigned the SGDID (LOCUS, REFERENCE, STRAIN, FILE, PATHWAY).';
COMMENT ON COLUMN sgdid.date_created IS 'Date the record was entered into the database.';
COMMENT ON COLUMN sgdid.sgdid_status IS 'State of the SGDID (Primary, Secondary, Deleted, Unassigned).';
COMMENT ON COLUMN sgdid.source_id IS 'FK to SOURCE.SOURCE_ID.';
COMMENT ON COLUMN sgdid.created_by IS 'Username of the person who entered the record into the database.';
COMMENT ON COLUMN sgdid.description IS 'Comment about or reason why the SGDID was deleted.';
ALTER TABLE sgdid ADD CONSTRAINT sgdid_uk UNIQUE (format_name);
ALTER TABLE sgdid ADD CONSTRAINT sgdid_subclass_ck CHECK (SUBCLASS IN ('LOCUS','FILE','STRAIN','REFERENCE','PATHWAY'));
ALTER TABLE sgdid ADD CONSTRAINT sgdid_status_ck CHECK (SGDID_STATUS IN ('Primary','Secondary','Deleted','Unassigned'));
CREATE INDEX sgdid_source_fk_index ON sgdid (source_id);
