es_mapping = {
    "settings":{
        "index":{
            "analysis":{
                "analyzer":{
                    "default":{
                        "type":"standard"
                    },
                    "autocomplete":{
                        "type":"custom",
                        "filter":[
                            "lowercase",
                            "autocomplete_filter"
                        ],
                        "tokenizer":"standard"
                    },
                    "raw":{
                        "type":"custom",
                        "filter":[
                            "lowercase"
                        ],
                        "tokenizer":"keyword"
                    }
                },
                "filter":{
                    "autocomplete_filter":{
                        "min_gram":"1",
                        "type":"edge_ngram",
                        "max_gram":"20"
                    }
                }
            },
            "number_of_replicas":"1",
            "number_of_shards":"5"
        }
    },
    "mappings":{
        "searchable_item":{
            "properties":{
                "biological_process":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "category":{
                    "type":"string"
                },
                "observable":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "qualifier":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "references":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "phenotype_loci":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "keys":{
                    "type":"string"
                },
                "chemical":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "mutant_type":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "go_loci":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "author":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "journal":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "institution":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "work_phone":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "year":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "reference_loci":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "cellular_component":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "description":{
                    "type":"string"
                },
                "summary":{
                    "type":"string"
                },
                "feature_type":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "href":{
                    "type":"string"
                },
                "molecular_function":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                },
                "name":{
                    "type":"string",
                    "analyzer":"autocomplete",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "analyzer":"raw"
                        }
                    }
                },
                "go_id":{
                    "type":"string"
                },
                "name_description":{
                    "type":"string"
                },
                "phenotypes":{
                    "type":"string",
                    "fields":{
                        "raw":{
                            "type":"string",
                            "index":"not_analyzed"
                        }
                    }
                }
            }
        }
    }
}
