heritage_url = None
backend_url = 'https://www.yeastgenome.org/webservice'
secret_key = 'secret key here'
sender = 'email address here'
author_response_file = 'file with full path here'
compute_url = ''
# elasticsearch_address = 'http://localhost:9200'
elasticsearch_address = 'http://ec2-34-221-214-103.us-west-2.compute.amazonaws.com:9200'
log_directory = None
