heritage_url = None
backend_url = 'https://be.staging.yeastgenome.org/'
secret_key = 'secret key here'
sender = 'email address here'
author_response_file = 'file with full path here'
compute_url = ''
# elasticsearch_address = 'http://localhost:9200'
elasticsearch_address = 'https://es.staging.yeastgenome.org/'
log_directory = None
